### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by amirhosseinalikhah** [vbmithr/ocaml-bip32-ed25519#3]
hi, 
I'm getting this error as I compile the program. what's the matter?

root@DESKTOP-R8DRA4T:~/OB/src# ocamlopt -o progprog unix.cmxa bip32_ed25519.ml
File "bip32_ed25519.ml", line 7, characters 15-26:
Error: Unbound module Bigstring

thanks in advance ...

**Comment by vbmithr** [comment]
Use [opam](http://opam.ocaml.org).
